const fs = require('fs');
const path = require('path');

/**
 * Aggregates OpenTofu plan summaries into a single Markdown report for PR comments.
 *
 * Environment Variables Required:
 * - GITHUB_RUN_ID: The ID of the current workflow run.
 * - GITHUB_REPOSITORY: The owner and name of the repository.
 */

const runId = process.env.GITHUB_RUN_ID;
const repository = process.env.GITHUB_REPOSITORY;

const modules = [
  { id: 'vpc', name: 'global/vpc' },
  { id: 'gke', name: 'global/gke' },
  { id: 'iam', name: 'global/iam' },
];

let body = `### 🛡️ Infrastructure Plan Summary (Run #${runId})\n\n`;

for (const { id, name } of modules) {
  const summaryPath = path.join('summaries', `summary-${id}`, 'plan_summary.txt');
  let summary = 'Summary not available.';

  if (fs.existsSync(summaryPath)) {
    summary = fs.readFileSync(summaryPath, 'utf8').trim();
  }

  body += `<details>\n`;
  body += `<summary><b>${name}</b> (Click to expand)</summary>\n\n`;
  body += `\`\`\`\n${summary}\n\`\`\`\n\n`;
  body += `**To apply this plan locally:**\n\n`;
  body += `1. Download the artifact:\n`;
  body += `\`\`\`bash\ngh run download ${runId} -n plan-${id} -D ${name}\n\`\`\`\n\n`;
  body += `2. Apply the specific plan:\n`;
  body += `\`\`\`bash\ncd ${name} && tofu apply infra.tfplan\n\`\`\`\n\n`;
  body += `</details>\n\n`;
}

body += `*Note: Plan generated by GitHub Actions run [${runId}](https://github.com/${repository}/actions/runs/${runId}).*`;

fs.writeFileSync('report.md', body);
console.log('Successfully generated report.md');
