const fs = require('fs');
const path = require('path');

/**
 * Aggregates OpenTofu plan summaries and Trivy security scans into a single Markdown report for PR comments.
 *
 * Environment Variables Required:
 * - GITHUB_RUN_ID: The ID of the current workflow run.
 * - GITHUB_REPOSITORY: The owner and name of the repository.
 */

const runId = process.env.GITHUB_RUN_ID;
const repository = process.env.GITHUB_REPOSITORY;
const serverUrl = process.env.GITHUB_SERVER_URL || 'https://github.com';

const modules = [
  { id: 'backend', name: 'global/backend' },
  { id: 'vpc', name: 'global/vpc' },
  { id: 'iam', name: 'global/iam' },
  { id: 'tailscale', name: 'global/tailscale' },
  { id: 'gke', name: 'global/gke' },
  { id: 'k8s', name: 'global/k8s' },
];

let body = `### CI Report (Run #${runId})\n\n`;
body += `#### OpenTofu Plans\n\n`;

for (const { id, name } of modules) {
  const summaryPath = path.join('summaries', `summary-${id}`, 'plan_summary.txt');
  const planPath = path.join('summaries', `plan-${id}`, 'infra.tfplan');
  const planExists = fs.existsSync(planPath);
  let summary = 'Summary not available.';

  if (fs.existsSync(summaryPath)) {
    summary = fs.readFileSync(summaryPath, 'utf8').trim();
  }

  body += `<details>\n`;
  body += `<summary><b>${name}</b> ${planExists ? '✅' : '❌'} (Click to expand)</summary>\n\n`;
  body += `\`\`\`\n${summary}\n\`\`\`\n\n`;

  if (planExists) {
    body += `**To apply this plan locally:**\n\n`;
    body += `1. Download the artifact:\n`;
    body += `\`\`\`bash\ngh run download ${runId} -n plan-${id} -D ${name}\n\`\`\`\n\n`;
    body += `2. Apply the specific plan:\n`;
    body += `\`\`\`bash\ncd ${name} && tofu apply infra.tfplan\n\`\`\`\n\n`;
  } else {
    const jobUrl = `${serverUrl}/${repository}/actions/runs/${runId}`;
    body += `❌ **Plan failed.** [View job logs](${jobUrl})\n\n`;
  }

  body += `</details>\n\n`;
}

body += `#### Security Audit (Trivy)\n\n`;

const trivyPath = path.join('summaries', 'trivy-results', 'trivy-results.json');

if (fs.existsSync(trivyPath)) {
  try {
    const trivyResults = JSON.parse(fs.readFileSync(trivyPath, 'utf8'));
    let totalIssues = 0;
    let issuesTable = `| Target | ID | Severity | Title | Message |\n| --- | --- | --- | --- | --- |\n`;
    let hasIssues = false;

    if (trivyResults.Results) {
      for (const result of trivyResults.Results) {
        if (result.Misconfigurations) {
          hasIssues = true;
          for (const misconf of result.Misconfigurations) {
            totalIssues++;
            issuesTable += `| ${result.Target} | ${misconf.ID} | ${misconf.Severity} | ${misconf.Title} | ${misconf.Message} |\n`;
          }
        }
      }
    }

    if (hasIssues) {
      body += `⚠️ **Found ${totalIssues} security misconfigurations (HIGH/CRITICAL).**\n\n`;
      body += issuesTable + `\n\n`;
    } else {
      body += `✅ **No high or critical security misconfigurations found.**\n\n`;
    }
  } catch (err) {
    body += `❌ **Error parsing Trivy results.**\n\n`;
  }
} else {
  body += `❓ **Security scan results not available.**\n\n`;
}

body += `*Note: Report generated by GitHub Actions run [${runId}](https://github.com/${repository}/actions/runs/${runId}).*`;

fs.writeFileSync('report.md', body);
console.log('Successfully generated report.md');
